config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "clubhouses#index"
  get 'users/:user_id/clubhouses/:id/join', to: 'clubhouses#join', as: 'user_clubhouse_join'
  get 'users/:user_id/clubhouses/:id/leave', to: 'clubhouses#leave', as: 'user_clubhouse_leave'
  
  resources :users do
   resources :clubhouses 
  end

  resources :clubhouses do  
    resources :posts
  end
  resources :posts do
    resources :comments
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?
    Clubhouse.all.each do |club|
      if user.clubhouse_ids.include?(club.id)
        can :read, club
      end
    end
    
    Clubhouse.all.each do |club|
      if user.id == club.creator_id
        can :delete, club
      end
    end
    #if user.clubhouse_id.include?(clubhouse.id)
     # can :read, Clubhouse 
    #can :read, Clubhouse, Clubhouse.all do |club|
    #  club.id == user.clubhouse_id
    #end
    #end
    
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/clubhouse.rb
class Clubhouse < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  belongs_to :clubhouse
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def email_required?
    false
  end
  def email_changed?
    false
  end
  
  # For ActiveRecord 5.1+
  def will_save_change_to_email?
    false
  end
  
  has_many :clubhouses
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/clubhouses_controller.rb
class ClubhousesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @clubhouses = Clubhouse.all
    end

    def new
        @clubhouse = Clubhouse.new
        @user = User.find(params[:user_id])
    end

    def create
        @clubhouse = Clubhouse.new(clubhouse_params)

        if @clubhouse.save
            redirect_to user_clubhouse_join_path(user_id: current_user.id, id: @clubhouse.id)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def show
        @clubhouse = Clubhouse.find(params[:id])
        @user = User.find(params[:user_id])
    end

    def join
        @clubhouse = Clubhouse.find(params[:id])
        @user = User.find(params[:user_id])
        @user.clubhouses << @clubhouse
        @clubhouse.users << @user

        redirect_to user_clubhouse_path(user_id: current_user.id, id: @clubhouse.id)
    end

    def leave
        @clubhouse = Clubhouse.find(params[:id])
        @user = User.find(params[:user_id])
        @clubhouse.users.delete(@user)
        @user.clubhouses.delete(@clubhouse)
        redirect_to root_path, status: :see_other
    end

    def destroy
        @clubhouse = Clubhouse.find(params[:id])
        @clubhouse.destroy

        redirect_to root_path, status: :see_other
    end

    private
    def clubhouse_params
        params.require(:clubhouse).permit(:name, :creator_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        @user = User.find(@comment.user_id)
        redirect_to clubhouse_post_path(clubhouse_id: params[:comment][:clubhouse_id], id: params[:post_id])
    end

    private
    def comment_params
        params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def show
        @clubhouse = Clubhouse.find(params[:clubhouse_id])
        @user = User.find(current_user.id)
        @post = Post.find(params[:id])
        @author = User.find(@post.user_id)
    end
    def new
        @post = Post.new
        @clubhouse = Clubhouse.find(params[:clubhouse_id])
        @user = User.find(params[:user_id])
    end

    def create
        @post = Post.new(post_params)
        @clubhouse = Clubhouse.find(params[:clubhouse_id])
        @user = User.find(current_user.id)

        if @post.save
            puts "Saved"
            redirect_to user_clubhouse_path(user_id: current_user.id, id: @clubhouse.id)
        else
            puts "not saved"
            puts :unprocessable_entity
            render :new, status: :unprocessable_entity
        end
    end

    private

    def post_params
        params.require(:post).permit(:title, :body, :user_id, :clubhouse_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(current_user.id)
        @clubhouse = @user.clubhouses
        @post = @user.posts
        @comments = @user.comments
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubhouses_helper.rb
module ClubhousesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clubhouses/_clubhouse.html.erb
<%= link_to clubhouse.name, user_clubhouse_path(user_id: current_user.id, id: clubhouse.id), {class: 'clubhouse-link'} %>

app/views/clubhouses/index.html.erb
<div class="clubhouse-index"> 

    <%= link_to new_user_clubhouse_path(current_user.id) do %>
        <div class="add-clubhouse"> 
            <svg class="yellow-plus" width="45" height="45" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 6L12 18" stroke-width="2" stroke-linecap="round"/>
                <path d="M18 12L6 12" stroke-width="2" stroke-linecap="round"/>
            </svg>
            <p> Add clubhouse </p>
        </div>
    <% end %>

    <h1> Available Clubhouses </h1>

    <div class="clubhouse-list">
        <%= render @clubhouses %>
    </div>
</div>

app/views/clubhouses/new.html.erb
<div class="new-club">
<h2> Create a clubhouse </h2>

<%= form_with model: [@user, @user.clubhouses.build ] do |form| %>
    <div class="club-form-label">
        <%= form.label :name %>
        <%= form.text_field :name %>
        <%= form.hidden_field :creator_id, value: current_user.id %>
    </div>
    <div class="submit-button">
        <%= form.submit %>
    </div>
<% end %>

</div>

app/views/clubhouses/show.html.erb
<div class="clubhouse"> 
  <%show_author = can? :read, @clubhouse%>
    <% unless show_author%>
      <%= link_to user_clubhouse_join_path(current_user.id) do %>
          <div class="add-clubhouse"> 
              <svg class="yellow-plus" width="45" height="45" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M12 6L12 18" stroke-width="2" stroke-linecap="round"/>
                  <path d="M18 12L6 12" stroke-width="2" stroke-linecap="round"/>
              </svg>
              <p> Join clubhouse </p>
          </div>
      <% end %>
    <% else %>
      <h1> Welcome to the club <%= current_user.username %>! </h2>
    <% end %>

    <h1 class="clubhouse-name"><%= @clubhouse.name%></h1>
    <% if show_author%>
      <%= link_to new_clubhouse_post_path(user_id: current_user.id, clubhouse_id: @clubhouse.id) do %>
          <div class="add-post"> 
              <svg class="yellow-plus" width="45" height="45" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M12 6L12 18" stroke-width="2" stroke-linecap="round"/>
                  <path d="M18 12L6 12" stroke-width="2" stroke-linecap="round"/>
              </svg>
              <p> <%= "Post to #{@clubhouse.name}"%> </p>
          </div>
      <% end %>
    <% end %>

    <h3 class="posts-header">Posts</h3>
    <div class="post-list">
      <%= render @clubhouse.posts, can_show_author: show_author%>
    </div>

    <% if can? :delete, @clubhouse%>
      <%= link_to "Delete Clubhouse", user_clubhouse_path(@clubhouse), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      }%>

    <% elsif show_author%>
      <%= link_to "Leave Clubhouse", user_clubhouse_leave_path%>

    <%end%>
<div>

app/views/comments/_comment.html.erb
<div class="comment"> 
    <p class="author"> <%= User.find(comment.user_id).username %>
    <p class="comment-body"> <%= comment.body %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <h1> <%= link_to "Members Only", root_path %> </h1>
    <% unless current_user.nil? %>
      <h1 class="log-out"> <%= link_to "Log Out", destroy_user_session_path %> </h1>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<%= link_to clubhouse_post_path(clubhouse_id: post.clubhouse.id, id: post.id) do %>
    <div class="post-link">
        <h2>
            <%= post.title %>
        </h2>
        <%= "by #{post.user.username}" if can_show_author%>

        <p class="post-body">
            <%= "#{post.body[0..5]}..."%>
        <p>
    </div>
    <% end %>

app/views/posts/new.html.erb
<div class="new-post">
    <h1> Create a post </h1>

    <%= form_with model: [@clubhouse, @clubhouse.posts.build] do |form| %>
        <div class="post-form-label">
            <%= form.text_field :title, placeholder: "Title" %>
        </div>
        <div class="post-form-label post-form-body">
            <%= form.text_area :body, placeholder: "Put your thoughts here..." %>
        </div>

        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :clubhouse_id, value: @clubhouse.id %>

        <div class="submit-button">
            <%= form.submit user_id: @user.id %>
        </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="post"> 
    
    <h1> <%= @post.title%> </h1>

    <%show_author = can? :read, @clubhouse%>
    <% if show_author%>
        <h3> By <%= @author.username %> </h3>
    <% end %>

    <p class="body">
        <%= @post.body%>
    <p>
    <h2> Comments </h2>
    <%= render @post.comments %>
    
    <h2>Add a comment:</h2>
    <%= form_with model: [ @post, @post.comments.build ] do |form| %>
        <%= form.text_area :body %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :post_id, value: @post.id %>
        <%= form.hidden_field :clubhouse_id, value: @clubhouse.id %>
        <div>
            <%= form.submit %>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="user">
    <%= render @clubhouse%>
    <%= render @post, can_show_author: true%>
    <%= render %>
<div>